apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: 10.0.7.43
    http:
      paths:
      - backend:
          serviceName: go-app
          servicePort: 80
        path: /