apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-app-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: go-app-service
          servicePort: 80
        path: /