apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-app
  name: go-app
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: go-app
  sessionAffinity: None
  type: NodePort
